version: '3.8'

services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: alemeno_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  api:
    build: .
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/alemeno_db
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - db
      - redis
    # --- TAMBAHKAN INI ---
    volumes:
      - shared_tmp:/tmp

  worker:
    build: .
    command: celery -A app.worker.celery_app worker --loglevel=info
    env_file:
      - .env
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/alemeno_db
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - db
      - redis
    volumes:
      - shared_tmp:/tmp

volumes:
  postgres_data:
  shared_tmp: